# Generated by Django 6.1 on 2026-08-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tituloproyecto', models.TextField(blank=True, db_column='tituloProyecto')),
                ('descripcion', models.TextField(blank=True)),
                ('rol', models.TextField(blank=True)),
                ('tecnologias', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
